apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/cgawron/bin/kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: bookme
  name: bookme
  namespace: bookme
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookme
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/cgawron/bin/kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/traefik: 'true'
        io.kompose.service: bookme
    spec:
      containers:
        - env:
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  key: EMAIL_FROM
                  name: bookme-secret
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: EMAIL_PASSWORD
                  name: bookme-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: bookme-secret
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: CLIENT_ID
                  name: bookme-secret
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: CLIENT_SECRET
                  name: bookme-secret
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: bookme
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  key: CLIENT_URL
                  name: bookme
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: bookme
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: bookme
          image: ghcr.io/fhswf/book_me/backend:1.10.0
          name: bookme
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 2Gi
      restartPolicy: Always
      automountServiceAccountToken: false
status: {}
