version: "3"

services:
  app:
    container_name: bookme
    image: bookme:latest
    restart: always
    build: .
    env_file:
      - docker.env
    ports:
      - "127.0.0.1:47001:5000"
    links:
      - mongo-bookme

  mongo-bookme:
    container_name: mongo-bookme
    image: mongo
    volumes:
      - /opt/bookme/mongo:/data/db
