apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookme
  namespace: argocd
spec:
  destination:
    namespace: book_me
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/fhswf/book_me'
      path: k8s
      targetRevision: HEAD
    - repoURL: 'https://github.com/fhswf/book_me'
      path: client/k8s
      targetRevision: HEAD
    - repoURL: 'https://github.com/fhswf/book_me'
      path: backend/k8s
      targetRevision: HEAD
  syncPolicy:
    automated: {}
