name: Deployment

on:
  deployment:
      types: [created]
  release:
      types: [published, updated]
  registry_package:
      types: [published, updated]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hopper
    steps:
        - run: echo "Deploying ${{ github.event.client_payload.package.name }} ${{ github.event.client_payload.package.version }} to ${{ github.event.client_payload.package.registry }}"
        